/*
 * JSONSchemaTools - Generators and validator for JSON schema, with abstract values
 *
 * Copyright 2022 University of Mons, University of Antwerp
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package be.ac.umons.jsonschematools.generator.exploration;

import java.util.Iterator;

import org.json.JSONException;
import org.json.JSONObject;

import be.ac.umons.jsonschematools.JSONSchema;
import be.ac.umons.jsonschematools.JSONSchemaException;

/**
 * An iterator over the documents that are generated by
 * {@link ExplorationGenerator}.
 * 
 * @author Gaëtan Staquet
 */
class ExplorationIterator implements Iterator<JSONObject> {

    private final JSONSchema schema;
    private final ChoicesSequence choices = new ChoicesSequence();
    private final ExplorationGenerator generator;
    private final int maxDocumentDepth;
    private final boolean canGenerateInvalid;
    private JSONObject nextDocument = null;

    ExplorationIterator(JSONSchema schema, int maxDocumentDepth, boolean canGenerateInvalid,
            ExplorationGenerator generator) {
        this.schema = schema;
        this.generator = generator;
        this.maxDocumentDepth = maxDocumentDepth;
        this.canGenerateInvalid = canGenerateInvalid;
        computeNextDocument();
    }

    @Override
    public boolean hasNext() {
        return nextDocument != null;
    }

    @Override
    public JSONObject next() {
        JSONObject document = nextDocument;
        computeNextDocument();
        return document;
    }

    @Override
    public String toString() {
        return this.choices.toString();
    }

    private void computeNextDocument() {
        if (choices.containsChoiceWithNextValue()) {
            try {
                nextDocument = generator.generateDocument(schema, maxDocumentDepth, canGenerateInvalid, choices);
            } catch (JSONException | JSONSchemaException e) {
                e.printStackTrace();
                nextDocument = null;
            }
        } else {
            nextDocument = null;
        }
    }
}
